[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[dependencies]
text_io = "0.1.12"
string-builder = "0.2.0"
regex = "1"
once_cell = "1"

[[bin]]
name = "compiler"
path = "src/compiler.rs"
